version: '3.8'

services:
  client-dev:
    image: node:18-alpine
    container_name: client-dev
    networks:
      - core_net
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
networks:
  core_net:
    external: true